// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwu7PmBPhy2snRBSFq8UI6AEH470P0ww',
    appId: '1:760804320276:web:a85dea381b9d1d2f95b301',
    messagingSenderId: '760804320276',
    projectId: 'playgroup-pals',
    authDomain: 'playgroup-pals.firebaseapp.com',
    storageBucket: 'playgroup-pals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZnTcF7CVEmCXJRXkYgMWWpLGAmcLK15U',
    appId: '1:760804320276:android:dfc84eb801137e9d95b301',
    messagingSenderId: '760804320276',
    projectId: 'playgroup-pals',
    storageBucket: 'playgroup-pals.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGwu7PmBPhy2snRBSFq8UI6AEH470P0ww',
    appId: '1:760804320276:web:e7751d4d88e577d295b301',
    messagingSenderId: '760804320276',
    projectId: 'playgroup-pals',
    authDomain: 'playgroup-pals.firebaseapp.com',
    storageBucket: 'playgroup-pals.firebasestorage.app',
  );

}